[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
#addopts = -vs --html=reports/report.html
addopts = -vs --html=reports/report.html --self-contained-html

markers =
    regression: 回归测试用例集
    smoke: 冒烟测试用例集
    slow: 运行较慢的测试
    skip: 跳过的测试